### ISSUE TITLE
Background-image dont work.

### ISSUE THREAD

**Issue by lordjbs** [leovoel/BeautifulDiscord#14]
I wanna change my background image with: `.app {
	background-image: url("http://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1444253482/DG2015-paris.jpg");
}` but it doesnt work! Can you help me?

**Comment by ARCofSpada** [comment]
Add this to your CSS.
```CSS
.theme-dark .layers { background: transparent !important; }
```

**Comment by leovoel** [comment]
that by itself is not enough i think. a lot of container elements have a background color, you'll have to make all those transparent first.

**Comment by lordjbs** [comment]
I made this what ArCofSpada said but it wont work: 
`
.theme-dark .layers { background: transparent !important; }
.app { background-image: url("http://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1444253482/DG2015-paris.jpg") !important;}
`

**Comment by leovoel** [comment]
yes, as i said before, many elements do have `background-color` set, you'll have to figure those out.

something like:
```css
.layers * { background: transparent !important; }
.layers { background-color: red !important; /* or whatever else... */ }
```

...would "work", but then it would affect too much.

here's a list of all rules with `background`/`background-color` declarations:
https://gist.github.com/leovoel/754e467872155730d8f2e1bd2e3a1687

it's quite long, and some stuff may not be necessary to modify, but should save you some time. you'll then need to do something like:

```css
.chat, .messages-wrapper /* ...and other classes you want to change the styling of */ {
  background: transparent !important;
}
```

hope that helps
