### ISSUE TITLE
Change font?

### ISSUE THREAD

**Issue by EwolBash** [leovoel/BeautifulDiscord#72]
I have no experience with CSS. I've tried googling for an answer but what I've tried so far hasn't worked.

I'm using Linux and the default font on Linux just looks hideous. 

I've managed to change the font from within the client and it looks good, but obviously it doesn't save between reloads hence why I installed beautifuldiscord.

```
beautifuldiscord --css discord.css 
Found Discord under /opt/discord

Done!

You may now edit your /home/esux/discord.css file,
which will be reloaded whenever it's saved.

```

The font I want to use is called 'Noto Sans'. (or honestly any font that looks OK on linux)

Any help you can provide would be appreciated. (Especially considering this isn't a bug.)

**Comment by Pierce01** [comment]
you can change the client's font by using a font face

https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp

**Comment by Bauke** [comment]
You can change the font to any that are installed on your computer by using `font-family`, using these selectors it gets changed everywhere:

```css
::placeholder,
body,
button,
input,
select,
textarea {
  /* Replace 'Inter' with the font of your choosing */
  font-family: 'Inter', sans-serif;
}
```
